/**
 * __TITLE__ — a switch-accessible __FAMILY__ game for the Narbehouse
 * Accessibility Hub.
 *
 * Generated by tools/create-benny-game. It extends BennyGame, so pause/back,
 * TTS announcements, and the switch-scanning wiring come for free. Fill in the
 * two overrides below — getScanTargets() and onSelect() — to build the game.
 *
 * Loaded as an IIFE global via <script src> in the browser, and exported via
 * CommonJS so the conformance test can require() it under jest + jsdom.
 */
(function () {
  "use strict";

  const GLOBAL =
    typeof window !== "undefined"
      ? window
      : typeof globalThis !== "undefined"
        ? globalThis
        : {};

  // BennyGame is provided by ../../../shared/benny-app.js (script tag) or by a
  // require() in the conformance test. Resolve it from the global scope.
  const BennyGame = GLOBAL.BennyGame;

  /**
   * @class __NAME__
   * @extends BennyGame
   *
   * A __FAMILY__-family starter. The constructor seeds a small set of cells;
   * getScanTargets() exposes them to the scanner and onSelect() reacts to a
   * switch press. Replace the stub logic with your real game.
   */
  class __NAME__ extends BennyGame {
    constructor(options = {}) {
      super(options);
      this.cells = [];
    }

    /**
     * Build the playfield once the game is mounted. Each cell is a real
     * <button> so it is keyboard- and screen-reader-friendly out of the box.
     * @override
     */
    onMount() {
      const root =
        this.root || (typeof document !== "undefined" ? document.body : null);
      if (!root || !root.ownerDocument) return;
      const doc = root.ownerDocument;

      // __FAMILY__ starter: a handful of selectable cells. Tune the count and
      // labels for your game (a board/grid wants a matrix; arcade/quiz fewer).
      const labels = ["One", "Two", "Three", "Four"];
      this.cells = labels.map((label, i) => {
        const cell = doc.createElement("button");
        cell.type = "button";
        cell.className = "game-cell";
        cell.setAttribute("data-index", String(i));
        cell.setAttribute("aria-label", label);
        cell.textContent = label;
        root.appendChild(cell);
        return cell;
      });
    }

    /**
     * Return the ordered list of elements the scanner steps through. A concrete
     * game MUST override this — here it is the playfield cells.
     * @returns {HTMLElement[]}
     * @override
     */
    getScanTargets() {
      return this.cells;
    }

    /**
     * React to a switch selection. A concrete game MUST override this — here it
     * just announces the chosen cell. Replace with real game logic.
     * @param {HTMLElement} target
     * @param {number} index
     * @override
     */
    onSelect(target, index) {
      const label = target?.getAttribute?.("aria-label") || `Cell ${index + 1}`;
      this.speak(`You picked ${label}`);
    }

    /**
     * Inherited from BennyGame: fired when the player chooses Back on the pause
     * overlay. Hook this up to your hub navigation.
     * @override
     */
    onBack() {
      if (typeof window !== "undefined" && window.history) {
        window.history.back();
      }
    }
  }

  // --- Browser auto-mount -------------------------------------------------
  // Only mounts when the playfield root exists, so require()ing this module in
  // a test (no #game-root) never triggers a mount.
  if (typeof document !== "undefined") {
    const boot = () => {
      const root = document.getElementById("game-root");
      if (root) new __NAME__().mount(root);
    };
    if (document.readyState === "loading") {
      document.addEventListener("DOMContentLoaded", boot);
    }
  }

  // --- Dual export: IIFE global + CommonJS --------------------------------
  if (typeof window !== "undefined") {
    window.__NAME__ = __NAME__;
  }
  if (typeof module !== "undefined" && module.exports) {
    module.exports = __NAME__;
  }
})();
