/**
 * @jest-environment jsdom
 *
 * Conformance test for __TITLE__ (generated by tools/create-benny-game).
 *
 * It loads the REAL shared accessibility stack — ScanController + BennyGame —
 * and the game's app.js, then asserts the game honours the accessible-by-default
 * contract: it overrides the two abstract hooks and wires a live ScanController
 * on mount. This passes out of the box; keep it green as you build the game.
 */

// Order matters: scan-core then benny-app populate window.ScanController and
// window.BennyGame, which app.js extends at evaluation time.
require("../../../../shared/scan-core");
require("../../../../shared/benny-app");
const __NAME__ = require("./app");

describe("__NAME__ conformance", () => {
  beforeEach(() => {
    document.body.innerHTML = "";
  });

  test("subclasses BennyGame", () => {
    expect(typeof __NAME__).toBe("function");
    expect(__NAME__.prototype).toBeInstanceOf(window.BennyGame);
  });

  test("overrides the abstract getScanTargets() and onSelect() hooks", () => {
    expect(typeof __NAME__.prototype.getScanTargets).toBe("function");
    expect(typeof __NAME__.prototype.onSelect).toBe("function");
    // The overrides must NOT be the throwing base-class stubs.
    expect(__NAME__.prototype.getScanTargets).not.toBe(
      window.BennyGame.prototype.getScanTargets,
    );
    expect(__NAME__.prototype.onSelect).not.toBe(
      window.BennyGame.prototype.onSelect,
    );
  });

  test("getScanTargets() does not throw and returns an array", () => {
    const game = new __NAME__();
    expect(() => game.getScanTargets()).not.toThrow();
    expect(Array.isArray(game.getScanTargets())).toBe(true);
  });

  test("mount() wires a real ScanController", () => {
    document.body.innerHTML = '<main id="game-root"></main>';
    const game = new __NAME__();
    game.mount(document.getElementById("game-root"));

    expect(game.scan).toBeInstanceOf(window.ScanController);

    game.teardown();
    expect(game.scan).toBeNull();
  });
});
